Serilog:
  Using: [ "Serilog.Sinks.Console", "Serilog.Sinks.Loki" ]
  MinimumLevel: 
    Default: Information
    Override:
      SS14: Verbose
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: "Information"
      
  WriteTo:
    - Name: Console
      Args:
        OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"
        
  Enrich: [ "FromLogContext" ]

  #Loki:
  #  Address: "http://localhost:3100"
  #  Name: "Test"

#Changelog:
#  GitHubSecret: "foobar"
#  ChangelogBranchName: "changelog-test"
#  GitHubToken: 'your_github_personal_access_token_here'
#  ChangelogRepo: 'C:\Users\Pieter-Jan Briers\Projects\ss14-changelog'
#  ChangelogRepoRemote: 'https://github.com/space-wizards/space-station-14.git'
#  DelaySeconds: 5